### PR TITLE
Optimize viewer

### PR DESCRIPTION
**Pull request by damiencaselli**
This PR brings a couple of enhancements for the Poppy Ergo Jr web viewer.

One optimisation was done to improve code consistency, code now follows more or less [Google javascript code conventions](https://google.github.io/styleguide/javascriptguide.xml).
This could – and should — should be ran against JSLint/JSHint/JSCS/<insert your weapon of choice here> to ensure code consistency through all pull requests.

Another optimisation was to batch API calls to avoid cancelled xhr requests due to fast refresh rates. It should save some browser resources and make execution more stable.
This comes in addition to [extending Pypot HTTP API](https://github.com/poppy-project/pypot/commit/39262a8789d4138a1f65222f8b4f6d393ad07528).

Finally, `.gitignore` file was updated to ignore only `lib` folder at project's root level..

### CODE REVIEW

**Comment by jgrizou** [comment]
Cool, lots of formatting indeed!

I have no time to check before next week. If it works please merge it and deploy it on the gh-page.

Do you have the rights on this repo or not yet?

**Comment by damiencaselli** [comment]
It works, but it still lacks documentation (this actually the main caveat).

I have the rights to perform the merge, but I'd gladly use a review :smiley:

**Comment by show0k** [comment]
Btw, we are just lacking a fun name to put the threejs part in a separated repository. Any idea ?

**Comment by damiencaselli** [comment]
`poppy-viewer` `poppeep` `poppy-droy`?

**Comment by jgrizou** [comment]
Why not keep it on the same repo? it is only relevant for the ergojr

Otherwise: ```poppy-ergojr-viewer```

**Comment by damiencaselli** [comment]
There is a super-top-secret-classified rumor that we may, one day, expand the viewer to other robots. That's why @show0k mentioned a robot agnostic name.

**Comment by pierre-rouanet** [comment]
Should it still be merged while the secret project is private?

**Comment by show0k** [comment]
@damiencaselli  pushed now in poppy-simu repository.

**Pull request closed without merging**
