### PR TITLE
Remove simulator and gh-pages build code

### PR DESCRIPTION
**Pull request by damiencaselli**
gh-pages branch and simulator have been replaced by a dedicated
repository (https://github.com/poppy-project/poppy-simu).

@show0k can you greenlight this PR?

### CODE REVIEW

**Comment by show0k** [comment]
We'll to make poppy-simu public before deleting it.

**Comment by jgrizou** [comment]
I would like to keep it for historical reasons. If we remove links to it, people should not be confused, not even knowing it existed.

**Comment by damiencaselli** [comment]
@jgrizou the viewer code will not be updated at all on this repository, and could stop working if API changes.
If you really want to keep track of the viewer inside this repository, we could either add a mention that viewer is now another repository on its own, or add it as a subrepo.

**Comment by jgrizou** [comment]
No I don't want the new viewer to be a sub-repo or anything like that, neither to have the code from this repo to stay compatible at all. 

I would just like to keep the code as it is in this repo somewhere here so I can refer to it in the future for further experimenting, e.g. with the physics.

**Comment by pierre-rouanet** [comment]
I think we should at least put it in the branch. It might get really confusing otherwise. People are still managing to use the old humanoid repo for instance.

**Comment by show0k** [comment]
:+1: I vote also for putting in a separated branch. In the same way, we should keep in this branch all the shapes made with open-scad which are not longer used in the printed robots.

**Comment by jgrizou** [comment]
Makes sense. Also keep the branch called ```adding -physics```.

I think the branch ```demo-live-threejs```, ```refactoring-simulator```, and  ```pypot-interface``` are branches about threejs viewer that have been merged in master. So they can be removed, providing we keep the current master as a new branch.

**Comment by jgrizou** [comment]
Sorry let me correct something. @show0k do you want to remove the hardware folder? or just the previous files in the releases?

The hardware folder is a nice example of how to use robotis-scad, which is interesting for makers and advanced users that want to have fun.

If we start removing everything useful for advanced users, let's stop using github and give access to a zip file on our website :)

**Comment by show0k** [comment]
`Sorry let me correct something. @show0k do you want to remove the hardware folder? or just the previous files in the releases?`
The releases are not made to be updated. I just want to update the hardware folder to make it correspond to the actual poppy-ergo-jr.
`The hardware folder is a nice example of how to use robotis-scad, which is interesting for makers and advanced users that want to have fun.`
Yes, doubtless, but it is outdated and no longer used for the hardware parts. We could keep it also in a branch, and add a reference in the readme.

**Comment by jgrizou** [comment]
Keeping it in a branch is like killing it, no one looks into branches.

It would be a pity to reduce the hardware folder to only stl files, it goes a bit against what we prone for the poppy project. What about having the following in hardware:
- README.md which explains the two options, making clear what is in each folder
- onshape (folder) which contains a README.md explaining how to find the project on onshape and duplicate it, as well as exports of stls, and maybe other formats.
- openscad (folder) with all open-scad as currently with a README.md explaining how to generate the stls

Anyhow for the beginners, the most important thing is to have the stl available in one-click on the website. Well even to have the robot kit available in one-click. 

The overall aim remains to enpower people (not only teachers but hackers, makers, artists, students...) to create and customize robots. Providing a variety of examples is a big part of it.

**Comment by show0k** [comment]
Ok for the double subfolder in /hardware.

**Comment by damiencaselli** [comment]
I'll open an issue dedicated to this.

**Pull request closed without merging**
